services:
  - type: web
    name: ec-exhibits-server
    env: node
    plan: free
    repo: https://github.com/media-code-now/ec-exhibits
    branch: main
    root: server
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
